### ISSUE TITLE
perform mint: minting coins from message: unauthorized account: invalid request

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/cw-tokenfactory-issuer#13]
I encountered an issue while testing the steps on the main README.

Everything worked until this step: 

```
await signer.mint({ toAddress: owner.address, amount: "100" })
```

Error
```
Uncaught:
Error: Query failed with (18): failed to execute message; message index: 0: dispatch: submessages: perform mint: minting coins from message: unauthorized account: invalid request
    at QueryClient.queryUnverified (/Users/web/.npm/_npx/4bf4005c775bf2eb/node_modules/@cosmjs/stargate/build/queryclient/queryclient.js:106:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.simulate (/Users/web/.npm/_npx/4bf4005c775bf2eb/node_modules/@cosmjs/stargate/build/modules/tx/queries.js:50:34)
    at async SigningCosmWasmClient.simulate (/Users/web/.npm/_npx/4bf4005c775bf2eb/node_modules/@cosmjs/cosmwasm-stargate/build/signingcosmwasmclient.js:66:29)
    at async SigningCosmWasmClient.signAndBroadcast (/Users/web/.npm/_npx/4bf4005c775bf2eb/node_modules/@cosmjs/cosmwasm-stargate/build/signingcosmwasmclient.js:255:35)
    at async SigningCosmWasmClient.execute (/Users/web/.npm/_npx/4bf4005c775bf2eb/node_modules/@cosmjs/cosmwasm-stargate/build/signingcosmwasmclient.js:199:24)
```

My owner is:
```
....
  address: 'osmo1cyyzpxplxdzkeea7kwsydadg87357qnahakaks'
}
```

**Comment by Stphill0** [comment]
Hi @daniel-farina  kindly visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)

**Comment by iboss-ptk** [comment]
@daniel-farina  You need to set mint allowance first

```
await signer.set_minter({ "address": owner.address, "allowance": "100" })
```
